/* eslint-disable jsx-a11y/no-static-element-interactions */
"use client";
import { useEffect, useState } from "react";

type Farm = { health_score:number; status:"healthy"|"warning"|"critical"; farmer:{online:boolean;last_activity_seconds:number}; node:{synced:boolean;syncing:boolean;height:number}; farm:{plots:number;size_tib:number;estimated_time_to_win_seconds:number;failed_plots:number}; harvesters:{online:number;total:number}; wallet:{balance_xch:number;blocks_won:number;rewards_xch:number}; disks:Array<{name:string;used_percent:number;temperature_c:number|null;smart_healthy:boolean|null}>; alerts:Array<{severity:string;message:string}>; updated_at:string };
const demo:Farm={health_score:96,status:"healthy",farmer:{online:true,last_activity_seconds:18},node:{synced:true,syncing:false,height:6821943},farm:{plots:742,size_tib:73.4,estimated_time_to_win_seconds:1036800,failed_plots:0},harvesters:{online:2,total:2},wallet:{balance_xch:4.126,blocks_won:3,rewards_xch:6},disks:[{name:"Farm 01",used_percent:87,temperature_c:36,smart_healthy:true},{name:"Farm 02",used_percent:91,temperature_c:39,smart_healthy:true}],alerts:[],updated_at:new Date().toISOString()};
const duration=(s:number)=>s<60?`${s}s`:s<3600?`${Math.round(s/60)}m`:s<86400?`${Math.round(s/3600)}h`:`${Math.round(s/86400)} days`;
const dot=(ok:boolean)=><span className={`dot ${ok?"good":"bad"}`} aria-hidden="true"/>;

export default function Home(){
 const [data,setData]=useState<Farm>(demo); const [live,setLive]=useState(false); const [settingsOpen,setSettingsOpen]=useState(false); const [agentUrl,setAgentUrl]=useState(()=>typeof window==="undefined"?"":localStorage.getItem("chia-agent-url")||""); const [token,setToken]=useState(()=>typeof window==="undefined"?"":localStorage.getItem("chia-api-token")||"");
 useEffect(()=>{const load=()=>{if(!agentUrl||!token){setLive(false);return}fetch(`${agentUrl.replace(/\/$/,"")}/api/status`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.ok?r.json():Promise.reject()).then(v=>{setData(v);setLive(true)}).catch(()=>setLive(false))};load();const id=setInterval(load,30000);return()=>clearInterval(id)},[agentUrl,token]);
 const saveSettings=(event:React.FormEvent)=>{event.preventDefault();localStorage.setItem("chia-agent-url",agentUrl.replace(/\/$/,""));localStorage.setItem("chia-api-token",token);setSettingsOpen(false)};
 return <main>
  <header><div className="brand"><span className="mark">C</span><span>Chia Monitor</span></div><button className="connection" onClick={()=>setSettingsOpen(true)} aria-label="Configure agent connection"><span className={`pulse ${live?"":"demo"}`}/>{live?"Live":"Demo"}<span aria-hidden="true">⌄</span></button></header>
  <section className="hero" aria-label="Farm health"><div className="hero-copy"><p className="eyebrow">YOUR FARM IS</p><h1>{data.status==="healthy"?"Healthy":data.status==="warning"?"Needs attention":"Critical"}</h1><p>{data.alerts.length?`${data.alerts.length} active alert${data.alerts.length===1?"":"s"}`:"Everything is farming normally."}</p></div><div className="score" style={{"--score":`${data.health_score*3.6}deg`} as React.CSSProperties}><div><strong>{data.health_score}</strong><span>/100</span></div></div></section>
  <section className="quick-grid">
   <article><div className="icon green">●</div><div><span>Farmer</span><strong>{dot(data.farmer.online)}{data.farmer.online?"Online":"Offline"}</strong><small>Activity {duration(data.farmer.last_activity_seconds)} ago</small></div></article>
   <article><div className="icon blue">↗</div><div><span>Full node</span><strong>{dot(data.node.synced)}{data.node.synced?"Synced":data.node.syncing?"Syncing":"Offline"}</strong><small>Height {data.node.height.toLocaleString()}</small></div></article>
   <article><div className="icon lime">⌁</div><div><span>Farm size</span><strong>{data.farm.size_tib.toFixed(1)} TiB</strong><small>{data.farm.plots.toLocaleString()} plots</small></div></article>
   <article><div className="icon purple">▣</div><div><span>Harvesters</span><strong>{data.harvesters.online} / {data.harvesters.total}</strong><small>{data.harvesters.online===data.harvesters.total?"All connected":"Connection issue"}</small></div></article>
  </section>
  <section className="stats"><article><span>Estimated time to win</span><strong>~{duration(data.farm.estimated_time_to_win_seconds)}</strong><small>Based on current netspace</small></article><article><span>Wallet balance</span><strong>{data.wallet.balance_xch.toFixed(3)} <i>XCH</i></strong><small>{data.wallet.blocks_won} blocks · {data.wallet.rewards_xch} XCH rewards</small></article></section>
  <section className="section-head"><div><p className="eyebrow">STORAGE</p><h2>Farm drives</h2></div><span>{data.disks.length} connected</span></section>
  <section className="drives">{data.disks.map(d=><article key={d.name}><div className="drive-top"><div><span>{d.name}</span><strong>{d.smart_healthy===false?"SMART warning":"Healthy"}</strong></div><b>{d.temperature_c==null?"—":`${d.temperature_c}°C`}</b></div><div className="bar"><i style={{width:`${d.used_percent}%`}}/></div><small>{d.used_percent}% used · {d.smart_healthy===null?"SMART unavailable":d.smart_healthy?"SMART passed":"SMART failed"}</small></article>)}</section>
  <footer><span>Updated {new Date(data.updated_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</span><span>{data.farm.failed_plots?`⚠ ${data.farm.failed_plots} failed plots`:"✓ No plot errors"}</span></footer>
  {settingsOpen&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSettingsOpen(false)}}><form className="modal" onSubmit={saveSettings}><div><p className="eyebrow">CONNECTION</p><h2>Connect your agent</h2><p>The URL stays on this device. Use your farm&apos;s local or Tailscale address.</p></div><label>Agent URL<input type="url" placeholder="http://100.x.y.z:8926" value={agentUrl} onChange={e=>setAgentUrl(e.target.value)} required/></label><label>API token<input type="password" placeholder="Your long API token" value={token} onChange={e=>setToken(e.target.value)} required/></label><div className="modal-actions"><button type="button" onClick={()=>setSettingsOpen(false)}>Cancel</button><button type="submit">Connect</button></div></form></div>}
 </main>
}
